trigger:
  branches:
    include:
    - master
  paths:
    include:
    - MijnThuis.Dashboard.App/*
    - pipelines-app-android.yml

pool:
  vmImage: 'windows-2022'

steps:

- task: CmdLine@2
  displayName: 'Install MAUI workload for dotnet CLI'
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages for MijnThuis.Dashboard.App.csproj'
  inputs:
    command: 'restore'
    projects: 'MijnThuis.Dashboard.App\MijnThuis.Dashboard.App.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish MijnThuis.Dashboard.App.csproj for net9.0-android'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'MijnThuis.Dashboard.App\MijnThuis.Dashboard.App.csproj'
    arguments: '-c Release -f net9.0-android /p:Platform=x64 --no-restore'

- task: CopyFiles@2
  displayName: 'Copy signed packages to ArtifactStagingDirectory'
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: |
      **/*-Signed.aab
      **/*-Signed.apk
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish signed packages to ArtifactStagingDirectory'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: MijnThuis.Dashboard.App