trigger:
  branches:
    include:
    - master
  paths:
    include:
    - MijnThuis.Worker/*
    - MijnThuis.Integrations/*
    - pipeline-worker.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (9.0)'
  inputs:
    packageType: sdk
    version: 9.0.203
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/MijnThuis.Worker.csproj

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: | 
      **/MijnThuis.Worker.csproj

- script: |
    dotnet publish ./MijnThuis.Worker --configuration "Release" --output ./MijnThuis.Worker/bin/Release/publish

- script: |
    cd ./MijnThuis.Worker
    docker build -t djohnnie/mijnthuis-worker .
    docker login -u '$(dockerId)' -p '$(dockerPwd)'
    docker push djohnnie/mijnthuis-worker