// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MijnThuis.DataAccess;

#nullable disable

namespace MijnThuis.DataAccess.Migrations
{
    [DbContext(typeof(MijnThuisDbContext))]
    [Migration("20241229112100_SolarHistory")]
    partial class SolarHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MijnThuis.DataAccess.Entities.SolarHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromSolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Production")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToHome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SysId"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("SysId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysId"));

                    b.ToTable("SOLAR_HISTORY", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
