// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MijnThuis.DataAccess;

#nullable disable

namespace MijnThuis.DataAccess.Migrations
{
    [DbContext(typeof(MijnThuisDbContext))]
    [Migration("20250210093136_EnergyHistory")]
    partial class EnergyHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MijnThuis.DataAccess.Entities.BatteryEnergyHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvailableEnergy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedStateOfHealth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RatedEnergy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StateOfCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StateOfHealth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SysId"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Date");

                    b.HasIndex("SysId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysId"));

                    b.ToTable("BATTERY_ENERGY_HISTORY", (string)null);
                });

            modelBuilder.Entity("MijnThuis.DataAccess.Entities.EnergyHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ActiveTarrif")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyPowerPeak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SysId"));

                    b.Property<decimal>("Tarrif1Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif1ExportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif1Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif1ImportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif2Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif2ExportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif2Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarrif2ImportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGasDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImportDelta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Date");

                    b.HasIndex("SysId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysId"));

                    b.ToTable("ENERGY_HISTORY", (string)null);
                });

            modelBuilder.Entity("MijnThuis.DataAccess.Entities.SolarEnergyHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromSolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Production")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToHome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SysId"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Date");

                    b.HasIndex("SysId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysId"));

                    b.ToTable("SOLAR_ENERGY_HISTORY", (string)null);
                });

            modelBuilder.Entity("MijnThuis.DataAccess.Entities.SolarPowerHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionFromSolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Production")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToBattery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToGrid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductionToHome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StorageLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SysId"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Date");

                    b.HasIndex("SysId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysId"));

                    b.ToTable("SOLAR_POWER_HISTORY", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
